version: '3'
services:
  db:
    image: postgres
  redis:
    image: redis:3.0
  web:
    build: .
    command: python3 manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/home/django/application
    ports:
      - "8000:8000"
    depends_on:
      - db
      - redis
